# Generated by Django 4.2.5 on 2023-09-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_alter_article_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',), 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
